[request_definition]
r = sub, guard, obj, act

[policy_definition]
p = sub, guard, obj, act

[policy_effect]
e = some(where (p.sub == r.sub))

[matchers]
m = r.sub == p.sub &&
    r.guard == p.guard &&
    r.obj == p.obj &&
    r.act == p.act